from manim import*
import functools
Text = functools.partial(Text, font="Comic Sans")
class S1(Scene):
    def construct(self):
        q = MathTex("x^{-x^x} = 2^{\sqrt2}").scale(2).to_edge(UL).shift(RIGHT*0.5)
        self.play(FadeIn(q,run_time=1.5))
        self.wait(1.5)
        # self.play(ques.animate.shift(LEFT*5+DOWN*4.5).scale(0.35))
        # self.wait(1.5)
        t1 = MathTex("x^{-n}={1\over{x^n}}").set_color(GRAY_A).to_edge(UR).shift(LEFT)
        self.play(FadeIn(t1,run_time=1.5))
        self.wait(1.5)
        t2 = MathTex("(n=x^x)").next_to(t1,DOWN,buff=1).set_color(GRAY_B)
        self.play(FadeIn(t2))
        self.wait()
        q2 = MathTex("{1\over ","x^{x^x}}"," = 2^{\sqrt2}").set_color(YELLOW_C).scale(1.5).next_to(q,DOWN,buff=1)
        self.play(TransformFromCopy(q,q2,run_time=2.5))
        self.wait(2.5)
        self.play(FadeOut(t2))
        self.wait()
        t3 = Tex("Let $x^{x^x}=$","$y$").next_to(q2,DOWN,buff=1).set_color(YELLOW_C).scale(2)
        bg1 = BackgroundRectangle(t3,buff=0.5).set_color(GRAY_A).set_opacity(0.5)
        self.play(Write(t3),FadeIn(bg1),run_time = 3.5)
        self.wait(3.5)
        self.play(t3[1].animate.move_to(q2[1]),FadeOut(bg1),FadeOut(t3[0]),FadeOut(q2[1]),run_time = 4.55)
        self.wait(2.5)
        q3 = MathTex("2^{\sqrt2} \cdot y = 1").set_color(BLUE).next_to(q2,DOWN,buff=0.75).scale(1.5)
        self.play(Write(q3,run_time=2),)
        self.wait(2.5)
        t4 = Tex("$x^n = 1$ , If $n$ = 0").set_color(GREEN).next_to(t2,DOWN)
        self.play(Write(t4,run_time=2.5))
        self.wait(2.5)
        q4 = MathTex("\implies y = 2^{-\sqrt2}").next_to(q3,DOWN,buff=1).set_color(RED).scale(1.5)
        self.play(Write(q4,run_time=2.5))
        self.wait(2.5)
        q5 = MathTex("={1\over 2^{\sqrt2}}").next_to(q4)
        self.play(FadeIn(q5),Indicate(t1),run_time = 2.5)
        self.wait(2.5)
        t6 = Tex("Now Lets just simplify $2^{\sqrt2}$").next_to(t4,DOWN,buff=1).set_color_by_gradient(RED,BLUE,GREEN).shift(LEFT)
        self.play(Create(t6),run_time=2)
        self.wait()
        self.play(*map(FadeOut, self.mobjects))
class S2(Scene):
    def construct(self):
        q = MathTex("x^{x^x} \ =  \ y \ = \ ","{1\over 2^{\sqrt2}} ").scale(2).shift(UP)
        self.play(FadeIn(q, run_time=1.5))
        self.wait(1.5)
        self.play(q.animate.shift(LEFT*5.5+DOWN*4.5).scale(0.35))
        self.wait(1.5)
        q2 = MathTex("2^{\sqrt2}").scale(1.5).to_edge(UL,buff=1)
        q3 = MathTex("\implies \ 4^{{1\over 2} \cdot \sqrt2}").next_to(q2,buff=1).set_color(YELLOW_A).scale(1.5)
        q4 = MathTex("\implies \ {4^{ {1 \over \sqrt2} }}").next_to(q3,buff=1).set_color(YELLOW_B).scale(1.5)
        t = Tex("(Multiplying and dividing by $\sqrt2$)").set_color(YELLOW).scale(1)
        self.play(Write(q2),run_time = 1.5)
        self.wait(1.5)
        self.play(Write(q3), run_time=2.5)
        self.wait(3.5)
        self.play(Write(q4),FadeIn(t), run_time=3.5)
        self.wait(3.5)
        self.play(FadeOut(t))
        self.wait()
        q5 = MathTex("1\over \sqrt2").next_to(q2,DOWN,buff=1).scale(1.5).set_color(BLUE_A)
        q6 = MathTex("\ = \ \sqrt{\sqrt{ {1\over4} }}").next_to(q5,buff=1).scale(1.5).set_color(BLUE_B)
        q7 = MathTex("\ = \ \left({1 \over 4 }\\right)^{ 1\over 4}").next_to(q6,buff=1).scale(1.5).set_color(BLUE_C)
        self.play(Write(q5), run_time=2.5)
        self.wait(3.5)
        self.play(Write(q6), run_time=2.5)
        self.wait(3.5)
        self.play(Write(q7), run_time=2.5)
        self.wait(3.5)
        self.play(FadeOut(q6),q7.animate.shift(LEFT*3.5),run_time=3.5)
        self.wait(3.5)
        q8 = MathTex("= (4)^{\left({1 \over 4 }\\right)^{ 1\over 4}}").next_to(q4,buff=1).set_color(YELLOW_C).scale(1.5)
        self.play(Write(q8),run_time = 1.5)
        self.wait(3.5)
        qx = q[1].copy()
        self.play(qx.animate.move_to(q8).shift(DOWN*2+LEFT*2).scale(2.5).set_color(RED_E),run_time=2.5)
        self.wait(2.5)
        q9 = MathTex("= \ {1 \over {(4)^{\left({1 \over 4 }\\right)^{ 1\over 4}}}}").next_to(qx,buff=1).set_color(RED_D).scale(1.5)
        self.play(Write(q9),run_time= 2.5)
        self.wait(3.5)
        q10 = MathTex("x^{x^x}  =   y  = \left({1\over 4}\\right)^{\left({1 \over 4 }\\right)^{ 1\over 4}}").next_to(q9,DOWN,buff=1).scale(1.5).set_color_by_gradient(GREEN_C,GREEN).shift(LEFT*2)
        self.play(Write(q10),run_time = 3.5)
        self.wait(4.5)
        B = Brace(q10,direction=LEFT)
        B_tex = B.get_tex("x={1\over4}").scale(1.5).set_color_by_gradient(RED,BLUE,GREEN).shift(LEFT*1.5)
        self.play(GrowFromCenter(B_tex),FadeIn(B),run_time = 2.5)
        self.wait(3.4)
        r = SurroundingRectangle(B_tex,buff=0.05)
        tx = Text("By Comparing:").next_to(q5,DOWN,buff=0.35).shift(RIGHT*2).scale(0.5)
        self.play(Create(r),FadeIn(tx),run_time = 2.5)
        self.wait(3.5)
        self.play(*map(FadeOut, self.mobjects))