from manim import *
class S1(Scene):
	def construct(self):
		q = Tex("Find number of digits of $2^{92}$").to_edge(UP).scale(2.25).shift(UP*5)
		f1 = SurroundingRectangle(q,buff=1,fill_color = GREEN_A , fill_opacity =0.2)
		self.play(Write(q),FadeIn(f1))
		self.wait()
		t = Tex("Let the number of digits = $x$").next_to(q,DOWN,buff=3).scale(2).set_color(RED)
		self.play(Write(t),run_time = 1.5)
		self.wait()
		t2 = MathTex("x \ = \ 2^{ 92 }").next_to(t,DOWN,buff=3).set_color(BLUE).scale(3)
		t3 = Text("Taking Log base 10 on both sides").to_edge(DOWN).scale(1).shift(DOWN*5)
		t4 = MathTex("\log_{ 10 } x"," = ","\log_{10} 2","^{92}").next_to(t2,DOWN,buff=3).set_color(GREEN).scale(3)
		t5 = MathTex("\log_{ 10 } x"," = ","92 \cdot ","\log_{10} 2").move_to(t4).set_color(GOLD).scale(3)
		self.play(Write(t2),run_time = 1.5)
		self.wait(1.5)
		self.play(Write(t3),run_time = 1.5)
		self.wait(1.5)
		self.play(Write(t4),FadeOut(t3),run_time = 1.5)
		self.wait(1.5)
		self.play(TransformMatchingTex(t4,t5),run_time=2.5)
		self.wait(2.5)
		b1 = Brace(t5[3],direction=DOWN,buff=0.5)
		b1_tex = b1.get_text("0.301").scale(3).shift(DOWN)
		self.play(FadeIn(b1),GrowFromCenter(b1_tex),run_time = 2)
		self.wait(1.5)
		self.play(b1_tex.animate.shift(UP*3).set_color(GOLD),FadeOut(b1),FadeOut(t5[3]),run_time = 3)
		self.wait(2)
		t6 = MathTex("27",".692").move_to(t4).set_color(GOLD).scale(3).shift(RIGHT*2)
		self.play(FadeOut(t5[2]),FadeOut(b1_tex),FadeIn(t6),run_time=2.5)
		self.wait(2.5)
		b2 = Brace(t6,direction=DOWN,buff=2.5)
		b2_tex = b2.get_text("""
		By convention ignore the \n
		decimal places and add 1
		""").shift(LEFT+DOWN).scale(1.5)
		self.play(FadeIn(b2),GrowFromCenter(b2_tex),run_time = 2)
		self.wait(1.5)
		t7 = MathTex("+1").next_to(t6,DOWN,buff=1).scale(3).set_color(MAROON).shift(LEFT*1.5)
		self.play(FadeOut(t6[1]),Create(t7),run_time = 2.5)
		self.wait(1.5)
		t8 = Text("= 28").next_to(t7,RIGHT*1.5,buff=0.8).shift(UP).set_color_by_gradient(RED,BLUE,GREEN).scale(2)
		self.play(Write(t8))
		self.wait()
		self.play(Indicate(t8),run_time = 2.5)
		self.wait(1.5)
		t9 = Tex("Bonus : Number of digits of $3^{92}$").next_to(b2_tex,DOWN).shift(LEFT+DOWN).set_color_by_gradient(RED,BLUE,GREEN)
		self.play(Create(t9),run_time = 2)
		self.wait(2)